# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-JSONRPC
version:      0.01
version_from: lib/Apache2/JSONRPC.pm
installdirs:  site
requires:
    Apache::Test:                  0
    JSON::Syck:                    0
    mod_perl2:                     2.000001

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
